spring:
  application:
    name: AuthorizationDemo
  datasource:
    url: jdbc:postgresql://192.168.30.77:5432/wido
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: wido
    name: widoData
logging:
  level:
    org:
      springframework:
        security: error

